function [fitresult, gof] = createFit(wave, spec)
%CREATEFIT(WAVE,SPEC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : wave
%      Y Output: spec
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Dec-2019 11:50:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( wave, spec );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [36125.956669846 533.023710267876 38.431892010762 5447.11132306854 847.316662068416 132.839849053674];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'spec vs. wave', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'wave', 'Interpreter', 'none' );
ylabel( 'spec', 'Interpreter', 'none' );
grid on


